import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Mark Hamil",
      email: "markhamil@test.com",
      password: bcrypt.hashSync("123456789", 8),
      isAdmin: true,
    },
    {
      name: "Tom Hanks",
      email: "tomhanks@test.com",
      password: bcrypt.hashSync("123456789", 8),
      isAdmin: false,
    },
  ],
  products: [
    /*{
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      //_id: "7",
      name: "Black backpack",
      category: "Others",
      image: "/images/black-fashion-backpack.jpg",
      price: 50,
      countInStock: 48,
      brand: "Louis Vuitton",
      rating: 4.5,
      numReviews: 5,
      description: "Black fashion backpack",
    },
    {
      // _id: "8",
      name: "Amazing watch",
      category: "Others",
      image: "/images/black-white-wrist-watches.jpg",
      price: 200,
      countInStock: 5,
      brand: "rolex",
      rating: 4.0,
      numReviews: 35,
      description: "Black or white wrist-watches",
    },
    {
      //_id: "9",
      name: "Red hand-bag",
      category: "Others",
      image: "/images/bright-red-purse-with-gold.jpg",
      price: 95,
      countInStock: 31,
      brand: "Luois Vuitton",
      rating: 3.5,
      numReviews: 68,
      description: "Bright red purse with gold",
    },
    {
      // _id: "10",
      name: "Brown hand-bag",
      category: "Others",
      image: "/images/brown-purse-with-shoulder-strap.jpg",
      price: 190,
      countInStock: 12,
      brand: "Luois Vuitton",
      rating: 2.8,
      numReviews: 130,
      description: "Brown purse with shoulder strap",
    },
    {
      // _id: "11",
      name: "Bracelet",
      category: "Others",
      image: "/images/buddha-bracelet-for-men.jpg",
      price: 20,
      countInStock: 8,
      brand: "AllFashion",
      rating: 5.0,
      numReviews: 64,
      description: "Buddha bracelet",
    },
    {
      // _id: "12",
      name: "Casual sweater",
      category: "Men's Fashion",
      image: "/images/casual-urban-menswear.jpg",
      price: 80,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 12,
      description: "Casual urban menswear",
    },
    */
    {
      // _id: "13",
      name: "Amazing black backpack",
      category: "Others",
      image: "/images/gold-zipper-on-black-fashion-backpack.jpg",
      price: 75,
      countInStock: 12,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 15,
      description: "Gold zipper on black fashion backpack",
    },
    {
      // _id: "14",
      name: "White T-shirt",
      category: "Women's Fashion",
      image: "/images/ladies-white-t-shirt.jpg",
      price: 30,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "Ladies white t-shirt",
    },
    {
      // _id: "15",
      name: "Light colored overcoat",
      category: "Men´s Fashion",
      image: "/images/man-poses-in-light-colored-overcoat.jpg",
      price: 300,
      countInStock: 8,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 5,
      description: "high quality product",
    },
    {
      // _id: "16",
      name: "Blue suit",
      category: "Men´s Fashion",
      image: "/images/mens-business-fashion.jpg",
      price: 450,
      countInStock: 12,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 15,
      description: "High quality blue suit",
    },
    {
      // _id: "17",
      name: "Leather jacket",
      category: "Women's Fashion",
      image: "/images/model-with-leather-jacket-over-shoulders.jpg",
      price: 200,
      countInStock: 12,
      brand: "AllFashion",
      rating: 4.0,
      numReviews: 1,
      description: "high quality product",
    },
    {
      //  _id: "18",
      name: "Red dress",
      category: "Women's Fashion",
      image: "/images/off-shoulder-red-cocktail-dress.jpg",
      price: 250,
      countInStock: 2,
      brand: "AllFashion",
      rating: 4.5,
      numReviews: 17,
      description: "Off shoulder red cocktail dress",
    },
    {
      // _id: "19",
      name: "Floral dress",
      category: "Women's Fashion",
      image: "/images/pink-floral-ummer-dress.jpg",
      price: 290,
      countInStock: 12,
      brand: "AllFashion",
      rating: 4.9,
      numReviews: 1,
      description: "Pink floral ummer dress",
    },
    {
      // _id: "20",
      name: "Red shirt",
      category: "Men's Fashion",
      image: "/images/professional-man-smiling.jpg",
      price: 49,
      countInStock: 1,
      brand: "Lacoste",
      rating: 5.0,
      numReviews: 85,
      description: "high quality product",
    },
    {
      // _id: "21",
      name: "Happy shirt",
      category: "Men's Fashion",
      image: "/images/young-man-in-bright-fashion.jpg",
      price: 30,
      countInStock: 200,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 5,
      description: "high quality product",
    },
    {
      // _id: "22",
      name: "Boho dress",
      category: "Women´s Fashion",
      image: "/images/womens-boho-dress.jpg",
      price: 70,
      countInStock: 10,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      //  _id: "23",
      name: "Comfortable combo",
      category: "Women´s Fashion",
      image: "/images/young-woman-in-comfortable-combo.jpg",
      price: 99,
      countInStock: 10,
      brand: "AllFashion",
      rating: 4.9,
      numReviews: 300,
      description: "high quality product",
    },
  ],
};
export default data;
